name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  jekyll:
    runs-on: ubuntu-latest
    env:
      BUNDLE_PATH: /tmp/nabang-blog-bundle
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Build site
        run: bundle exec jekyll build
