name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build
